version: "3.8"
services:
  catalog-service:
    depends_on:
      config-service:
        condition: service_healthy
      polar-postgres:
        condition: service_started
    image: "ghcr.io/vladstus/catalog-service:latest"
    container_name: "catalog-service"
    ports:
      - 9001:9001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=testdata
    restart: unless-stopped

  order-service:
    depends_on:
      config-service:
        condition: service_healthy
      polar-postgres:
        condition: service_started
    image: "order-service"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order

  config-service:
    image: "ghcr.io/vladstus/config-service:latest"
    container_name: config-service
    ports:
      - 8888:8888
    healthcheck:
      test: "curl --fail --silent config-service:8888/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 10s
    restart: unless-stopped

  polar-postgres:
    image: "postgres:14.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped