name: build-catalog-service-images
on:
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Change working directory
        run: |
          cd catalog-service
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: vladstus
          password: ${{ secrets.TOKEN_GH }}
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm/v8
          push: true
          tags: ghcr.io/vladstus/catalog-service:latest